package plugin

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// GenerateImports writes the Go source that links every plugin with code into
// package main: one blank import per directory under pluginsDir that HasCode,
// as importPrefix/<name>. Importing the package is what runs its init(), and
// init() is what calls Register.
//
// A directory the generator skips is one Discover also treats as no plugin
// (a leading '.' or '_'), so the two agree about what a plugin is.
func GenerateImports(pluginsDir, importPrefix string) ([]byte, error) {
	entries, err := os.ReadDir(pluginsDir)
	if err != nil && !os.IsNotExist(err) {
		return nil, err
	}
	var names []string
	for _, e := range entries {
		n := e.Name()
		if !e.IsDir() || strings.HasPrefix(n, ".") || strings.HasPrefix(n, "_") {
			continue
		}
		if HasCode(filepath.Join(pluginsDir, n)) {
			names = append(names, n)
		}
	}
	sort.Strings(names)

	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/plugingen from web/plugins; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Links in every plugin with Go code, whose init() registers it. Run\n")
	b.WriteString("// `go generate ./cmd/signaling` after adding or removing one.\n\n")
	b.WriteString("package main\n")
	if len(names) > 0 {
		b.WriteString("\nimport (\n")
		for _, n := range names {
			fmt.Fprintf(&b, "\t_ %q\n", importPrefix+"/"+n)
		}
		b.WriteString(")\n")
	}
	return format.Source(b.Bytes())
}
