#!/bin/bash

source .env

TARDIR=signaling
TARFILE=signaling.tgz

find ${TARDIR} -type f \( -wholename "*.html" -o -wholename "*.png" -o -wholename "*.conf" -o -wholename "*.py" -o -wholename "*.ico" -o -wholename "*.jpg" -o -wholename "*.js" -o -wholename "*.env_test" -o -wholename "*.sh" \) | tar cvfz ${TARFILE} -T -

scp -i ${SERVER_SSH_KEY} ${TARFILE} ${SERVER_SSH}:/opt/bitbang-test/${TARFILE}
ssh ${SERVER_SSH} -i ${SERVER_SSH_KEY} "cd /opt/bitbang-test; tar xvfz ${TARFILE}; cp signaling/.env_test signaling/.env; sudo systemctl restart signaling-test.service"
