// Code generated by cmd/plugingen from web/plugins; DO NOT EDIT.
//
// Links in every plugin with Go code, whose init() registers it. Run
// `go generate ./cmd/signaling` after adding or removing one.

package main
